 global:
   scrape_interval: 15s
   external_labels:
     monitor: 'codelab-monitor'

 scrape_configs:
   - job_name: 'cardano'
     scrape_interval: 5s
     static_configs:
       - targets: ['192.168.99.201:12798']
